apiVersion: v1
kind: Pod
metadata:
  name: test
spec:
  #restartPolicy: Never
  containers:
    - name: test
      image: alpine:3.12
      command: ["/bin/sh"]
      args: ["-c", "sleep 20 && echo jtthink"]